# Generated by Django 4.0.6 on 2022-08-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='UserSave', to='auctions.listing'),
        ),
    ]
